version: "3"

services:
  backend:
    build: backend
    env_file:
      - backend/.env
      - .env
    volumes:
      - ./backend:/app/
  backend_neural:
    build: backend_neural
    env_file:
      - backend_neural/.env
      - .env
    volumes:
      - ./backend_neural:/app/
  nginx:
    build: config
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/templates:/etc/nginx/templates:rw,cached
      - ./backend/static/:/app/static/
      - ./backend/media/:/app/media/
      - frontend_build:/app/frontend/build/
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    env_file:
      - .env
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  frontend:
    build: frontend
    env_file:
      - frontend/.env
      - .env
    volumes:
      - ./frontend/public:/app/frontend/public/
      - ./frontend/src:/app/frontend/src/
      - frontend_build:/app/frontend/build/

volumes:
  frontend_build:
  postgres_data:
